// <auto-generated />
namespace authentication_and_authorization.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class databascrate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(databascrate));
        
        string IMigrationMetadata.Id
        {
            get { return "202103051736163_databascrate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
